feat: Modal view inside Prospect/Customer
Roskus/prospect-flow-crm pull request #129
Opened 2023-03-04 12:54 UTC by elguitarraverde

Edit contact inside Prospect/Customer view #117

2023-03-06 22:33 UTC, gnovaro requested changes

2023-03-06 22:33 UTC, gnovaro commented on resources/views/lead_customer/show.blade.php
> +        var api_token = "{{ $_COOKIE['API-TOKEN'] }}";
Don't use direct php globals arrays better use safe laravel functions. 
```blade
{{ cookie('API-TOKEN') }}
```

2023-03-06 22:33 UTC, gnovaro commented on public/asset/js/ContactModalForm.js
> +            alert('The contact has been saved successfully.');
Please remove the alerts, change for console.log or add another way to show a message like we do with Twitter Boostrap Toast for notifications

2023-03-08 18:05 UTC, elguitarraverde commented
[fix alert to notification](https://github.com/Roskus/prospect-flow-crm/pull/129/commits/9b6d54d486c90cecdaedc94b713e2c5d0b53bbe2)

I have fixed the code by using the notifications script instead of the alert. 

I have eliminated the COOKIE to use the method that we define in the future.

2023-03-23 08:03 UTC, closed without merging