refactor generic email template
Roskus/prospect-flow-crm pull request #99
Opened 2023-02-18 18:18 UTC by elguitarraverde

refactor generic email template

![image](https://user-images.githubusercontent.com/2836337/219881931-146bd091-890d-48ac-80f6-eeb8d6dd4eaf.png)

![image](https://user-images.githubusercontent.com/2836337/219881959-d97498e4-edf5-4077-bf6d-843294831ef2.png)

2023-02-18 21:03 UTC, gnovaro requested changes
Looks great but the generic email is not generic anymore if we add data related only for ticket better should be duplicate the generic and implement a custom email view for the ticket feature

2023-02-20 15:38 UTC, elguitarraverde commented
@gnovaro 
We have added a default template for emails.
We have modified the generic view of the emails so that it uses the default template.
we have created a TicketStateChanged Mailable with its corresponding view.

2023-02-20 16:31 UTC, gnovaro submitted a review, later dismissed
Great job!

2023-02-20 16:32 UTC, gnovaro approved these changes

2023-02-20 16:32 UTC, merged